.TH PCL 1

.SH NAME

openni_image \- FIXME

.SH SYNOPSIS

.B openni_image [((<device_id> | <path-to-oni-file>) [-imagemode <mode>] | -l [<device_id>]| -h | --help)]

.SH DESCRIPTION

FIXME

.SH OPTIONS

.TP 5
\-h,\-\-help
shows this help

.TP 5
\-l <device\-id>
if device\-id is unset list all available devices
otherwise list all available modes for specified device
device_id may be #1, #2, ... for the first, second etc device in the
list or bus@address for the device connected to a specific usb\-bus /
address combination or <serial\-number>

.SH EXAMPLES

openni_image "#1"
    uses the first device.
openni_image "./temp/test.oni"
    uses the oni\-player device to play back oni file given by path.
openni_image \-l
    lists all available devices.
openni_image \-l "#2"
    lists all available modes for the second device
openni_image A00361800903049A
    uses the device with the serial number 'A00361800903049A'.
openni_image 1@16
    uses the device on address 16 at USB bus 1.


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
