.TH PCL 1

.SH NAME

pcl_ply2raw \- Convert from PLY to POV-Ray RAW triangle format.

.SH SYNOPSIS

.B pcl_ply2raw [OPTION] [[INFILE] OUTFILE]

.SH DESCRIPTION

Convert from PLY to POV-Ray RAW triangle format.

With no INFILE/OUTFILE, or when INFILE/OUTFILE is -, read standard input/output.

The following PLY elements and properties are supported.
  element vertex
    property float32 x
    property float32 y
    property float32 z
  element face
    property list uint8 int32 vertex_indices.

.SH OPTIONS

  -h, --help       display this help and exit
  -v, --version    output version information and exit

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
