.TH PCL 1

.SH NAME

pcl_virtual_scanner \- Generate point cloud from a 3d model.

.SH SYNOPSIS

.B pcl_virtual_scanner [options] <model.ply | model.vtk>

.SH DESCRIPTION

Generate point cloud from a 3d model.

.SH OPTIONS

.TP 5
\-object_coordinates <0|1>
save the dataset in object coordinates (1) or camera coordinates (0)

.TP 5
\-single_view <0|1>
take a single snapshot (1) or record a lot of camera poses on a view
sphere (0)

.TP 5
\-view_point <x,y,z>
set the camera viewpoint from where the acquisition will take place

.TP 5
\-target_point <x,y,z>
the target point that the camera should look at (default: 0, 0, 0)

.TP 5
\-organized <0|1>
create an organized, grid\-like point cloud of width x height (1), or
keep it unorganized with height = 1 (0)

.TP 5
\-noise <0|1>
add gausian noise (1) or keep the model noiseless (0)

.TP 5
\-noise_std <x>
use X times the standard deviation

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
