.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B FIXME [OPTIONS]

.SH DESCRIPTION

FIXME

.SH OPTIONS

Extract point clusters using pcl::EuclideanClusterExtraction. For more information, use: pcl_cluster_extraction -h
Syntax is: pcl_cluster_extraction input.pcd output.pcd <options>
  where options are:
                     -min X = use a minimum of X points peer cluster (default: 100)
                     -max X      = use a maximum of X points peer cluster (default: 25000)
                     -tolerance X = the spacial distance between clusters (default: 0.020000)

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
