.TH PCL 1

.SH NAME

pcl_voxel_grid \- Downsample a cloud using pcl::VoxelGrid.

.SH SYNOPSIS

.B pcl_voxel_grid input.pcd output.pcd <options>

.SH DESCRIPTION

Downsample a cloud using pcl::VoxelGrid.

.SH OPTIONS

.TP 5
\-leaf x,y,z
the VoxelGrid leaf size (default: 0.010000, 0.010000, 0.010000)

.TP 5
\-field X
filter data along this field name (default: z)

.TP 5
\-fmin  X
filter all data with values along the specified field smaller than this value (default: -inf)

.TP 5
\-fmax  X
filter all data with values along the specified field larger than this value (default: inf)

.TP 5
\-h
display help message


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
