.TH PCL 1

.SH NAME

pcl_transform_from_viewpoint \- FIXME

.SH SYNOPSIS

.B pcl_transform_from_viewpoint input.pcd output.pcd

.SH DESCRIPTION

Take the input point cloud and transform it according to its stored VIEWPOINT information.

.SH OPTIONS

FIXME

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
