.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B FIXME [OPTIONS]

.SH DESCRIPTION

FIXME

.SH OPTIONS

Syntax is: pcl_convert_pcd_ascii_binary <file_in.pcd> <file_out.pcd> 0/1/2 (ascii/binary/binary_compressed) [precision (ASCII)]


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
