.TH PCL 1

.SH NAME

pcl_cluster_extraction \- Extract point clusters using pcl::EuclideanClusterExtraction

.SH SYNOPSIS

.B pcl_cluster_extraction input.pcd output.pcd <options>

.SH DESCRIPTION

Extract point clusters using pcl::EuclideanClusterExtraction

.SH OPTIONS

.TP 5
\-min X
use a minimum of X points peer cluster (default: 100)

.TP 5
\-max X
use a maximum of X points peer cluster (default: 25000)

.TP 5
\-tolerance X
the spacial distance between clusters (default: 0.020000)

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
