.TH PCL 1

.SH NAME

pcl_crop_to_hull \- Filter a point cloud using the convex hull of another point cloud.

.SH SYNOPSIS

.B pcl_crop_to_hull hull_cloud.pcd input.pcd output.pcd <options>

.SH DESCRIPTION

Filter a point cloud using the convex hull of another point cloud.

.SH OPTIONS

.TP 5
\-alpha X
the hull alpha value (0+) (default: 1000.000000)


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
