.TH PCL 1

.SH NAME

pcl_openni_planar_convex_hull \- FIXME

.SH SYNOPSIS

.B pcl_openni_planar_convex_hull <device_id> <options>

.SH DESCRIPTION

FIXME

.SH OPTIONS

.TP 5
\-thresh X
set the planar segmentation threshold (default: 0.5)


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
