.TH PCL 1

.SH NAME

pcl_mesh_sampling \- Convert a CAD model to a point cloud using uniform sampling.

.SH SYNOPSIS

.B pcl_mesh_sampling input.{ply,obj} output.pcd <options>

.SH DESCRIPTION

Convert a CAD model to a point cloud using uniform sampling.

.SH OPTIONS

.TP 5
\-n_samples X
number of samples (default: 100000)

.TP 5
\-leaf_size X
the XYZ leaf size for the VoxelGrid \-\- for data reduction (default: 0.010000 m)


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
