.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B FIXME [OPTIONS]

.SH DESCRIPTION

FIXME

.SH OPTIONS

pcl_openni_grab_frame <filename> <options>

  filename: if no filename is provided a generic timestamp will be set as filename

  where options are:
                    -format = PCD file format (b=binary; bc=binary compressed; ascii=ascii; all=all) (default: bc)
                    -XYZ  = store just a XYZ cloud
                    -paused = start grabber in paused mode. Toggle pause by pressing the space bar
                              or grab single frames by just pressing the left mouse button.


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
