.TH PCL 1

.SH NAME

pcl_pcd2ply \- Convert a PCD file to PLY format.

.SH SYNOPSIS

.B pcl_pcd2ply input.pcd output.ply

.SH DESCRIPTION

Convert a PCD file to PLY format.

.SH OPTIONS

FIXME

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
