.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B pcl_openni_voxel_grid <device_id> <options>

.SH DESCRIPTION

FIXME

.SH OPTIONS

.TP 5
\-minmax min\-max
set the ApproximateVoxelGrid min\-max cutting values (default: 0\-5.0)

.TP 5
\-field  X
use field/dimension 'X' to filter data on (default: 'z')

.TP 5
\-leaf x, y, z
set the ApproximateVoxelGrid leaf size (default: 0.01)


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
