.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B FIXME [OPTIONS]

.SH DESCRIPTION

FIXME

.SH OPTIONS

Extract features from a point cloud. For more information, use: pcl_extract_feature -h
Syntax is: pcl_extract_feature input.pcd output.pcd <options>
  where options are:
                     -feature X = the feature descriptor algorithm to be used (default: FPFHEstimation)
                     -n_radius X = use a radius of Xm around each point to determine the neighborhood in normal estimation (default: 0.000000)
                     -n_k X      = use a fixed number of X-nearest neighbors around each point in normal estimation (default: 0.000000)
                     -f_radius X = use a radius of Xm around each point to determine the neighborhood in feature extraction (default: 0.000000)
                     -f_k X      = use a fixed number of X-nearest neighbors around each point in feature extraction(default: 0.000000)


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
