.TH PCL 1

.SH NAME

pcl_boundary_estimation \- Estimate boundary points using pcl::BoundaryEstimation.

.SH SYNOPSIS

.B pcl_boundary_estimation input.pcd output.pcd <options>

.SH DESCRIPTION

Estimate boundary points using pcl::BoundaryEstimation.

.SH OPTIONS

.TP 5
\-radius X
use a radius of Xm around each point to determine the neighborhood
(default: 0.000000)

.TP 5
\-k X
use a fixed number of X\-nearest neighbors around each point (default:
0)

.TP 5
\-thresh X
the decision boundary (angle threshold) that marks points as boundary
or regular (default: 1.570796)

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
