.TH PCL 1

.SH NAME

pcl_test_search_speed \- FIXME

.SH SYNOPSIS

.B pcl_test_search_speed [-pcd <pcd-file>] (-radius <radius> [-knn <k>] | -knn <k> )

.SH DESCRIPTION

FIXME

.SH OPTIONS

FIXME

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
