.TH PCL 1

.SH NAME

pcl_poisson_reconstruction \- FIXME

.SH SYNOPSIS

.B pcl_poisson_reconstruction input.pcd output.vtk <options>

.SH DESCRIPTION

FIXME

.SH OPTIONS

.TP 5
\-leaf X
the voxel size (default: 0.010000)

.TP 5
\-iso X
the iso level (default: 0.000000)

.TP 5
\-dot X
use the voxelization algorithm combined with a dot product
(i.e. MarchingCubesGreedy vs. MarchingCubesGreedyDot) (default: 1)

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
