.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B pcl_openni_tracking <device_id> [-C] [-g]

.SH DESCRIPTION

FIXME

.SH OPTIONS

.TP 5
\-C
initialize the pointcloud to track without plane segmentation

.TP 5
\-D
visualizing with non\-downsampled pointclouds.

.TP 5
\-P
not visualizing particle cloud.

.TP 5
\-fixed
use the fixed number of the particles.

.TP 5
\-d <value>
specify the grid size of downsampling (defaults to 0.01).


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
