.TH PCL 1

.SH NAME

pcl_add_gaussian_noise \- Add Gaussian noise to a point cloud.

.SH SYNOPSIS

.B Syntax is: pcl_add_gaussian_noise input.pcd output.pcd <options>

.SH DESCRIPTION

Add Gaussian noise to a point cloud.

.SH OPTIONS

.TP 5
\-sd X
the standard deviation for the normal distribution (default: 0.010000)

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
