.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B pcl_openni_planar_segmentation <device_id> <options>

.SH DESCRIPTION

FIXME

.SH OPTIONS



where options are:
         -thresh X        :: set the planar segmentation threshold (default: 0.5)


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
