.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B pcl_openni_mls_smoothing <device_id> <options>

.SH DESCRIPTION

FIXME

.SH OPTIONS



where options are:
                     -search_radius X = sphere radius to be used for finding the k-nearest neighbors used for fitting (default: 0)
                     -sqr_gauss_param X = parameter used for the distance based weighting of neighbors (recommended = search_radius^2) (default: 0)
                     -use_polynomial_fit X = decides whether the surface and normal are approximated using a polynomial or only via tangent estimation (default: 0)
                     -polynomial_order X = order of the polynomial to be fit (implicitly, use_polynomial_fit = 1) (default: 2)


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
