.TH PCL 1

.SH NAME

plyheader \- Extract the header from a PLY file.

.SH SYNOPSIS

.B plyheader [OPTION] [[INFILE] OUTFILE]

.SH DESCRIPTION

Extract the header from a PLY file.
With no INFILE/OUTFILE, or when INFILE/OUTFILE is -, read standard
input/output.


.SH OPTIONS

.TP 5
\-h, \-\-help
display this help and exit

.TP 5
\-v, \-\-version
output version information and exit


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
