.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B FIXME [OPTIONS]

.SH DESCRIPTION

FIXME

.SH OPTIONS

Syntax is: pcl_feature_matching <source-pcd-file> <target-pcd-file> <keypoint-method> <descriptor-type> <surface-reconstruction-method>
available <keypoint-methods>: 1 = Sift3D
                              2 = Harris3D
                              3 = Tomasi3D
                              4 = Noble3D
                              5 = Lowe3D
                              6 = Curvature3D

available <descriptor-types>: 1 = FPFH
                              2 = SHOTRGB
                              3 = PFH
                              4 = PFHRGB

available <surface-methods>:  1 = Greedy Projection
                              2 = Marching Cubes


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
