.TH PCL 1

.SH NAME

pcl_surfel_smoothing_test \- FIXME

.SH SYNOPSIS

.B pcl_surfel_smoothing_test normal_search_radius surfel_scale source_cloud destination_cloud

.SH DESCRIPTION

FIXME

.SH OPTIONS

FIXME

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
