.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B FIXME [OPTIONS]

.SH DESCRIPTION

FIXME

.SH OPTIONS

Filter a point cloud using the convex hull of another point cloud. For more information, use: pcl_crop_to_hull -h
Syntax is: pcl_crop_to_hull hull_cloud.pcd input.pcd output.pcd <options>
  where options are:
                     -alpha X = the hull alpha value (0+) (default: 1000.000000)


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
