.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B pcl_openni_uniform_sampling <device_id> <options>

.SH DESCRIPTION

FIXME

.SH OPTIONS

.TP 5
\-leaf X
set the UniformSampling leaf size (default: 0.01)

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
