.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B pcl_openni_tracking <device_id> [-C] [-g]

.SH DESCRIPTION

FIXME

.SH OPTIONS

  -C:  initialize the pointcloud to track without plane segmentation
  -D: visualizing with non-downsampled pointclouds.
  -P: not visualizing particle cloud.
  -fixed: use the fixed number of the particles.
  -d <value>: specify the grid size of downsampling (defaults to 0.01).


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
