.TH PCL 1

.SH NAME

pcl_transform_point_cloud \- FIXME

.SH SYNOPSIS

.B pcl_transform_point_cloud input.pcd output.pcd <options>

.SH DESCRIPTION

FIXME

.SH OPTIONS

           -trans dx,dy,dz           = the translation (default: 0.0, 0.0, 0.0)
           -quat w,x,y,z             = rotation as quaternion
           -axisangle ax,ay,az,theta = rotation in axis-angle form
           -matrix v1,v2,...,v8,v9   = a 3x3 affine transform
           -matrix v1,v2,...,v15,v16 = a 4x4 transformation matrix
   Note: If a rotation is not specified, it will default to no rotation.
         If redundant or conflicting transforms are specified, then:
           -axisangle will override -quat
           -matrix (3x3) will take override -axisangle and -quat
           -matrix (4x4) will take override all other arguments

.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
