.TH PCL 1

.SH NAME

FIXME \- FIXME

.SH SYNOPSIS

.B FIXME [OPTIONS]

.SH DESCRIPTION

FIXME

.SH OPTIONS

Add Gaussian noise to a point cloud. For more information, use: pcl_add_gaussian_noise -h
Syntax is: pcl_add_gaussian_noise input.pcd output.pcd <options>
  where options are:
                     -sd X = the standard deviation for the normal distribution (default: 0.010000)


.SH SEE ALSO

.TP
.B Home Page
http://www.pointclouds.org/

.SH AUTHOR

Willow Garage, Inc. and Open Perception, Inc.
